name: db-integration

replicaCount: 1

image:
  repository: 058264469194.dkr.ecr.ap-southeast-1.amazonaws.com
  name: ai-elevate/db-integration

imagePullPolicy: IfNotPresent
imagePullSecrets:
  - name: ecr-registry

service:
  type: ClusterIP
  port: 8088
  targetPort: 8088

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
