services:
  resume-scan:
    container_name: resume-scan
    build: ..
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_MODEL_NAME=${GOOGLE_MODEL_NAME}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL_NAME=${OPENAI_MODEL_NAME}
    ports:
      - 8501:8501
    restart: unless-stopped
    volumes:
      - ../:/app
