apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        version: {{ .Values.image.tag }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
          {{- if .Values.env }}
          {{- range $key, $value := .Values.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          {{- if .Values.secretEnv }}
          {{- range $envVar, $config := .Values.secretEnv }}
          - name: {{ $envVar }}
            valueFrom:
              secretKeyRef:
                name: {{ $config.from }}
                key: {{ $config.key }}
          {{- end }}
          {{- end }}
          {{- if or .Values.secrets .Values.configs }}
          volumeMounts:
          {{- range .Values.secrets }}
            - name: {{ .name }}-volume
              mountPath: {{ .mountPath }}
              readOnly: true
          {{- end }}
          {{- range .Values.configs }}
            - name: {{ .name }}-volume
              mountPath: {{ .mountPath }}
              readOnly: true
          {{- end }}
          {{- end }}
          {{- if .Values.healthCheck.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.healthCheck.path }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthCheck.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthCheck.path }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if or .Values.secrets .Values.configs }}
      volumes:
      {{- range .Values.secrets }}
        - name: {{ .name }}-volume
          secret:
            secretName: {{ .name }}
      {{- end }}
      {{- range .Values.configs }}
        - name: {{ .name }}-volume
          configMap:
            name: {{ .name }}
      {{- end }}
      {{- end }}
