apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "chart.fullname" . }}-secrets-manager
  labels:
    {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "chart.fullname" . }}-secrets-manager
  labels:
    {{- include "chart.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "chart.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "chart.fullname" . }}-secrets-manager
  apiGroup: rbac.authorization.k8s.io
