# .streamlit/secrets.toml

GEMINI_API_KEY = "AIzaSyACkJVUGYmMkmqGLSF7cxIxAWhOBEz_XCI"
GEMINI_MODEL_NAME = "gemini-1.5-flash"

# If you use OpenAI, add your key here
# OPENAI_API_KEY = "YOUR_OPENAI_API_KEY_HERE"
